AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for a clojure-lambda function.

# SAM Reference Docs
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html

Globals:
  Function:
    Timeout: 20

Resources:
  ClojureLambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      MemorySize: 256
      PackageType: Image
      #Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/custom/my-lambda-execution-role-here"
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            Description: Event that triggers the lambda every 30 minutes
            ScheduleExpression: rate(30 minutes)
            State: ENABLED
    Metadata:
      DockerContext: ./
      Dockerfile: Dockerfile
      DockerTag: clojure-lambda-1.0.0

Outputs:
  ClojureLambda:
    Description: "Clojure Lambda Function ARN"
    Value: !GetAtt ClojureLambda.Arn
  ClojureLambdaIamRole:
    Description: "IAM Role auto created for Clojure Lambda Function"
    Value: !GetAtt ClojureLambdaRole.Arn
